### ISSUE TITLE
Roadmap v0.1.3

### ISSUE THREAD

**Issue by diessica** [diessica/unit.styl#2]
- [ ] Cleaner and easier documentation similar to [nib](https://github.com/tj/nib).
- [ ] Tests using [stylus-test-runner](https://github.com/timjgleeson/stylus-test-runner).
- [ ] Add keywords to `package.json`, like **rem**, **unit fallback** etc.
